### ISSUE TITLE
Implementation of Energy score

### ISSUE THREAD

**Issue by dhaivat1729** [asharakeh/probdet#1]
Hi,

This is a great work. I am working on a very similar problem and would like to feature this as a baseline. Would it be possible to get a pointer for implementation of energy score that was presented in section 3.4 in the paper.

**Comment by asharakeh** [comment]
@dhaivat666 [here is the implementation](https://github.com/asharakeh/probdet/blob/368bd0b69e0339106504387b64f13723a80ca966/src/probabilistic_modeling/probabilistic_generalized_rcnn.py#L738) in one of the probabilistic models.

Let me know if you have any further questions.

**Comment by dhaivat666** [comment]
Thank you for your super quick response. I will have a look and ask if I am stuck anywhere.
