### ISSUE TITLE
Implementation of DETR-NLL

### ISSUE THREAD

**Issue by Andy-ggg** [asharakeh/probdet#5]
Hallo @asharakeh, first of all, thank you for your wonderful work. I am very interested in your work and also have some questions about the implementation of **DETR**.

1. Can you explain why the predicted covariance of the bounding box for DETR-NLL detection is too large?
2. What is the meaning of the digit in transform_mat in probabilistic_detr_predictor.py.

Thank you!

**Comment by asharakeh** [comment]
Hey @Andy-ggg , sorry for the late reply.

1. The reason can be found in the experiments section of our paper: https://arxiv.org/abs/2101.05036.
2. Each object detector predicts a particular representation of the bounding box. The transform mat takes this representation and standardize it to be top left bottom right corner representation. This helps us use one evaluator/visualizer for all models.

Hope this helps.
